const data = [
  { dessert: "Gingerbread", calories: 356, protein: 3.9 },
  { dessert: "Nougat", calories: 360, protein: 37 },
  { dessert: "Jelly Bean", calories: 375, protein: 0 },
  { dessert: "Lollipop", calories: 392, protein: 0 },
  { dessert: "Honeycomb", calories: 408, protein: 6.5 },
  { dessert: "Chocolate Cake", calories: 320, protein: 4 },
  { dessert: "Apple Pie", calories: 280, protein: 2.5 },
  { dessert: "Vanilla Ice Cream", calories: 200, protein: 3 },
  { dessert: "Strawberry Shortcake", calories: 280, protein: 3.5 },
  { dessert: "Blueberry Muffin", calories: 250, protein: 5 },
  { dessert: "Pancakes", calories: 320, protein: 6 },
  { dessert: "Waffles", calories: 400, protein: 4.5 },
  { dessert: "Cinnamon Roll", calories: 420, protein: 5.2 },
  { dessert: "Croissant", calories: 320, protein: 4.8 },
  { dessert: "Bagel", calories: 280, protein: 6 },
  { dessert: "Donut", calories: 360, protein: 4.5 },
  { dessert: "Sugar Cookies", calories: 180, protein: 2 },
  { dessert: "Oatmeal Raisin Cookies", calories: 220, protein: 2.5 },
  { dessert: "Peanut Butter Cookies", calories: 250, protein: 3 },
  { dessert: "Chocolate Chip Cookies", calories: 230, protein: 2.5 },
  { dessert: "Brownie", calories: 280, protein: 4 },
  { dessert: "Pecan Pie", calories: 350, protein: 5.5 },
  { dessert: "Cheesecake", calories: 320, protein: 3 },
  { dessert: "Lemon Tart", calories: 250, protein: 1.8 },
  { dessert: "Banana Split", calories: 400, protein: 4.5 },
  { dessert: "Cherry Pie", calories: 380, protein: 4 },
  { dessert: "Pumpkin Pie", calories: 300, protein: 3.5 },
  { dessert: "Key Lime Pie", calories: 320, protein: 2.5 },
  { dessert: "Coconut Macaroons", calories: 180, protein: 1.5 },
  { dessert: "Caramel Popcorn", calories: 250, protein: 3 },
];

export default data;
